
site_name: HelMoRo
site_url: https://example.com/

  
nav:
    - Introduction: index.md
    - Hardware: 
        - Bill of Materials: hardware/bill_of_materials.md
        - CAD: hardware/cad.md
        - Electronic System Architecture: hardware/electronic_system_architecture.md
        - Assembly Instructions: hardware/assembly_instructions.md
    - Software: software.md
    - Collaboration: collaboration.md
    - About: about.md

theme:
  name: material
  logo: assets/logos/Helbling_Logo_weiss.png
  favicon: assets/logos/Helbling_Favicon.png
  palette:
    scheme: default
    primary: custom 
    accent: custom 



  font:
    text: Sora
  features:
    #  - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight



copyright: >
  Copyright &copy; 2023 Helbling Technik Zürich 

plugins:
  #- privacy:
  #  enabled: !ENV [CI, false]
  - search:
      lang: 
        - en
        - de
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - table-reader


markdown_extensions:
  - markdown_include.include
  - attr_list
  - tables
  - toc:
      permalink: True

extra_css:
  - stylesheets/extra.css
