
site_name: HelMoRo
site_url: https://helbling-technik.github.io/HelMoRo/

software_repo_url: https://github.com/Helbling-Technik/HelMoRo-software
hardware_repo_url: https://github.com/Helbling-Technik/HelMoRo

  
nav:
    - Home: index.md
    - Description: description.md
    - Hardware: 
        - Bill of Materials: hardware/bill_of_materials.md
        - CAD: hardware/cad.md
        - Electronic System Architecture: hardware/electronic_system_architecture.md
        - Assembly Instructions: hardware/assembly_instructions.md
    - Software:
        - Introduction: software/01_software_introduction.md
        - Quick Start Guide:  software/02_quick_start_guide.md
        - Detailed Usage Guide:  software/03_detailed_guide.md
        - Installation: software/04_installation_guide.md
        - Software Architecture: software/05_software_architecture.md 
        - Algorithms: software/06_algorithms.md
    - Collaboration: collaboration.md
    - About: about/about.md

theme:
  name: material
  custom_dir: docs/.overrides
  logo: assets/logos/Helbling_Logo_weiss.png
  favicon: assets/logos/Helbling_Favicon.png
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
    primary: custom 
    accent: custom   

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: custom 
    accent: custom   

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    primary: custom 
    accent: custom 


  font:
    text: Sora
  features:
    #  - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight



copyright: >
  Software is shared under the BSD-3 license. <br> 
  CAD and mechanics design files are shared under the Creative Commons CC-BY-4.0. <br>
  <br>
  Copyright &copy; 2024 Helbling Technik Zürich 

extra:
  generator: false

  social:
  - icon: fontawesome/solid/house
    link: https://helbling.ch/en
  - icon: fontawesome/brands/github
    link: https://github.com/Helbling-Technik
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/helbling/

plugins:
  #- privacy:
  #  enabled: !ENV [CI, false]
  - search:
      lang: 
        - en
        - de
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - table-reader


markdown_extensions:
  - markdown_include.include
  - attr_list
  - tables
  - toc:
      toc_depth: 3
      permalink: True

extra_css:
  - stylesheets/extra.css
