
site_name: HelMoRo
site_url: https://example.com/

  
nav:
    - Introduction: index.md
    - Hardware: 
        - Bill of Materials: hardware/bill_of_materials.md
        - Electronic System Architecture: hardware/electronic_system_architecture.md
        - Assembly Instructions: hardware/assembly_instructions.md
    - Software: article.md
    - Collaboration: article.md
    - About: mkdocs_docu.md

theme:
  name: material
  logo: assets/logos/Helbling_Logo_weiss.png
  favicon: assets/logos/Helbling_Favicon.png
  palette:
    scheme: default
    primary: indigo
    accent: light blue



  font:
    text: Sora
  features:
    #  - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2016 - 2023 Helbling Technik Zürich –
  <a href="#__consent">Change cookie settings</a>

plugins:
  #- privacy:
  #  enabled: !ENV [CI, false]
  - search:
      lang: 
        - en
        - de
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - table-reader


markdown_extensions:
  - markdown_include.include
  - attr_list
  - tables
  - toc:
      permalink: True

