site_name: HelMoRo
site_url: https://example.com/
theme:
  name: material
  logo: assets/logos/Helbling_Logo_weiss.png
  favicon: assets/logos/Helbling_Favicon.png
  palette:
    scheme: slate
    # To change with https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors
    primary: indigo
    accent: light blue
  font:
    text: Sora
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigations.tabs.sticky
    - toc.integrate
plugins:
  #- privacy:
  #  enabled: !ENV [CI, false]
  - search:
      lang: 
        - en
        - de
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2016 - 2023 Helbling Technik Zürich –
  <a href="#__consent">Change cookie settings</a>
  
  
nav:
    - Home: index.md
    - Hardware: article.md
    - Software: article.md
    - About: mkdocs_docu.md