name: Build and Deploy Website

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache environment
        run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Restore and use cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: mkdocs-material-${{ env.cache_id }}

      - name: Install dependencies
        run: |
          pip install mkdocs-material markdown-include mkdocs-table-reader-plugin openpyxl

      - name: Build documentation
        run: mkdocs build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache environment
        run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Restore and use cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: mkdocs-material-${{ env.cache_id }}

      - name: Install dependencies
        run: |
          pip install mkdocs-material markdown-include mkdocs-table-reader-plugin openpyxl

      - name: Deploy documentation
        run: mkdocs gh-deploy --force



